"use client";

import { ClerkProvider } from "@clerk/nextjs";
import {
  useQuery,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Nav from "@/components/Nav";

import { UserProvider } from "@/lib/context/user";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QueryClientProvider client={queryClient}>
        <html lang="en" className="h-full w-full">
          <body className={`h-full w-full ${inter.className}`}>
            <Nav />
            <Suspense fallback={<div>loading child route...</div>}>
              {children}
            </Suspense>
          </body>
        </html>
      </QueryClientProvider>
    </ClerkProvider>
  );
}
