"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Nav from "@/components/Nav";

import { UserProvider } from "@/lib/context/user";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Nav />
          <Suspense fallback={<div>loading child route...</div>}>
            {children}
          </Suspense>
        </UserProvider>
      </body>
    </html>
  );
}
